// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://usdpkuchysffhiceklhi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVzZHBrdWNoeXNmZmhpY2VrbGhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyMzg2OTQsImV4cCI6MjA2MTgxNDY5NH0.nmP9cbAlgeTyHtgJJtOgsvYhhNbibnTdSvXcsAfBX1o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
