// This file is automatically generated. Do not edit it directly.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      agents: {
        Row: {
          id: string;
          name: string;
          email: string;
          phone: string | null;
          photo_url: string | null;
          bio: string | null;
          user_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          email: string;
          phone?: string | null;
          photo_url?: string | null;
          bio?: string | null;
          user_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          email?: string;
          phone?: string | null;
          photo_url?: string | null;
          bio?: string | null;
          user_id?: string | null;
          created_at?: string;
        };
      };
      properties: {
        Row: {
          id: string;
          title: string;
          description: string | null;
          price: number;
          location: string;
          address: string | null;
          type: string;
          category: string;
          bedrooms: number;
          bathrooms: number;
          area: number;
          year_built: number | null;
          parking: number | null;
          featured: boolean;
          created_at: string;
          updated_at: string;
          agent_id: string | null;
        };
        Insert: {
          id?: string;
          title: string;
          description?: string | null;
          price: number;
          location: string;
          address?: string | null;
          type: string;
          category: string;
          bedrooms: number;
          bathrooms: number;
          area: number;
          year_built?: number | null;
          parking?: number | null;
          featured?: boolean;
          created_at?: string;
          updated_at?: string;
          agent_id?: string | null;
        };
        Update: {
          id?: string;
          title?: string;
          description?: string | null;
          price?: number;
          location?: string;
          address?: string | null;
          type?: string;
          category?: string;
          bedrooms?: number;
          bathrooms?: number;
          area?: number;
          year_built?: number | null;
          parking?: number | null;
          featured?: boolean;
          created_at?: string;
          updated_at?: string;
          agent_id?: string | null;
        };
      };
      property_images: {
        Row: {
          id: string;
          property_id: string;
          url: string;
          is_main: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          property_id: string;
          url: string;
          is_main?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          property_id?: string;
          url?: string;
          is_main?: boolean;
          created_at?: string;
        };
      };
      property_features: {
        Row: {
          id: string;
          property_id: string;
          feature: string;
        };
        Insert: {
          id?: string;
          property_id: string;
          feature: string;
        };
        Update: {
          id?: string;
          property_id?: string;
          feature?: string;
        };
      };
      contact_messages: {
        Row: {
          id: string;
          name: string;
          email: string;
          phone: string | null;
          message: string;
          property_id: string | null;
          agent_id: string | null;
          status: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          email: string;
          phone?: string | null;
          message: string;
          property_id?: string | null;
          agent_id?: string | null;
          status?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          email?: string;
          phone?: string | null;
          message?: string;
          property_id?: string | null;
          agent_id?: string | null;
          status?: string;
          created_at?: string;
        };
      };
      team_members: {
        Row: {
          id: string;
          name: string;
          role: string;
          bio: string | null;
          photo_url: string | null;
          order_index: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          role: string;
          bio?: string | null;
          photo_url?: string | null;
          order_index?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          role?: string;
          bio?: string | null;
          photo_url?: string | null;
          order_index?: number;
          created_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
  };
}